add pagination
canonical/assets.ubuntu.com pull request #246
Opened 2024-08-26 00:27 UTC by goulinkh

## Done

- Add pagination with per_page option between 20 (default) and 100
- Parse available file extensions from the list of files in the DB

## QA

- 

## Issue / Card

Fixes #242

2024-11-29 06:43 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/22f066c7-ace0-4135-8259-e7b36a42a56a)
I suppose there used to be support for several file types

2024-11-29 06:46 UTC, immortalcodes commented
Also there is already work going on assets improvement and we have some features on this branch
https://github.com/canonical/assets.ubuntu.com/tree/feature_assets_improvement
Pagination was something that we were planning to do in this cycle and get it to this branch.

2024-11-29 10:26 UTC, goulinkh commented
> ![image](https://private-user-images.githubusercontent.com/92226302/390988854-22f066c7-ace0-4135-8259-e7b36a42a56a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjY5MjgsIm5iZiI6MTczMjg2NjYyOCwicGF0aCI6Ii85MjIyNjMwMi8zOTA5ODg4NTQtMjJmMDY2YzctYWNlMC00MTM1LTgyNTktZTdiMzZhNDJhNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3NTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjVhYjRlMTQ3ZDhhNGZhN2U0ZGRmNWE2YjJlNTUyODNmYjM2ZWRlODQ2Y2JjMmMyNWI0NjQxNzdlM2Q5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JWiXaoJRuxXRrCM3RA3H0PVXPn6klAv8YVtfevD6aYs) I suppose there used to be support for several file types

The new implementation gets the extensions from the database, having an empty list means that there are no assets in the database.

2024-12-02 09:25 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/a148d3e5-99f0-48b4-8bd2-e2d64e411c2e)
Slight inconsistency in numbering

2024-12-02 09:27 UTC, immortalcodes commented
Sorting with filename will not be useful if it is using hash codes and not the actual file names.
![image](https://github.com/user-attachments/assets/5d60cdf6-ea93-4677-a925-5d7127aae8d1)

2024-12-02 10:58 UTC, immortalcodes requested changes
This is really good work and is going to be quite helpful for entire team.
My comments are mostly edge cases and nitpicking. Once those seem fine we can merge it.
Thanks for this Awesome PR!

2024-12-02 10:58 UTC, immortalcodes commented on webapp/services.py
> +            .offset((max(page, 1) - 1) * max(per_page, 10))
Why a maximum here, isn't per_page always defined to be 20 when called, even so why a max between 10 when by default we call it with 20

2024-12-17 12:07 UTC, immortalcodes approved these changes

2024-12-17 12:08 UTC, immortalcodes commented
LGTM!
These features will be loved!

2024-12-18 15:13 UTC, merged